-- 부모의 형질을 모두 가지는 대장균 찾기
SELECT CE.ID,
       CE.GENOTYPE,
       PE.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA CE
JOIN ECOLI_DATA PE
ON CE.PARENT_ID = PE.ID
AND CE.GENOTYPE & PE.GENOTYPE = PE.GENOTYPE
ORDER BY CE.ID;